apiVersion: v1
kind: Service
metadata:
  name: {{ include "apus-platform.api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apus-platform.componentLabels" (dict "ctx" . "component" "api") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "apus-platform.componentSelectorLabels" (dict "ctx" . "component" "api") | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
